apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooth-caries-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caries-detection
  template:
    metadata:
      labels:
        app: caries-detection
    spec:
      containers:
      - name: caries-detection-container
        image: gcr.io/pacific-diode-435602-h0/caries-detection:latest
        ports:
        - containerPort: 8080 # Change if your app uses a different port
        env:
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: PORT
          value: "8080" # Change if your app uses a different port
        resources:
          requests:
            memory: "512Mi" # Request a reasonable amount of memory
            cpu: "500m" # Request half a CPU core
          limits:
            memory: "1Gi" # Set a memory limit of 1GB
            cpu: "1000m" # Set a CPU limit of 1 CPU core
