apiVersion: v1
kind: Service
metadata:
  name: caries-detection
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080 # Change if your app uses a different port
  selector:
    app: caries-detection
